// ============================================
// data-core → Astro 構建期數據橋
// 用途：把 data-core（瀏覽器全局數據）在 node 端 vm 沙箱載入，
//      dump 成 Astro 可 import 的 ESM 模塊（src/data/positions.generated.ts）。
//      令阅读站（門索引 + 220 位次頁）由 data-core 單一真相生成，杜絕手維護分裂。
// 運行：node data-core/emit-astro.mjs
// 產物：src/data/positions.generated.ts
// ============================================
import fs from "fs";
import vm from "vm";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");

// vm 沙箱 + window 墊片（與 build.mjs 同範式）
const ctx = { window: {}, console, Math, Map, Set, JSON, Array, Object, String, RegExp };
ctx.globalThis = ctx;
vm.createContext(ctx);
const load = (rel) => vm.runInContext(fs.readFileSync(path.join(__dirname, rel), "utf8"), ctx, { filename: rel });

// 按 index.html 順序載入（data.js 會 merge auto+manual+door15）
load("data/positions-auto.js");
load("data/positions-manual.js");
load("data.js");

const W = ctx.window;
const POSITIONS = W.POSITIONS;
const DOORS = W.DOORS;
if (!Array.isArray(POSITIONS) || POSITIONS.length !== 220) {
  console.error(`✗ POSITIONS 不為 220 位（實際 ${POSITIONS && POSITIONS.length}）`); process.exit(1);
}
if (!Array.isArray(DOORS) || DOORS.length !== 15) {
  console.error(`✗ DOORS 不為 15 門（實際 ${DOORS && DOORS.length}）`); process.exit(1);
}

// 位次名→slug 反查（data.js 已構建；可能為 Map）
const n2s = W.POSITION_NAME_TO_SLUG;
const nameToSlug = (n2s instanceof Map) ? Object.fromEntries(n2s) : (n2s || {});

// 緊湊 JSON → 嵌為 JS 字符串字面量，運行時 JSON.parse（避免 TS 對 700KB 字面量做深度類型檢查）
const lit = (obj) => `JSON.parse(${JSON.stringify(JSON.stringify(obj))})`;

const out = `// AUTO-GENERATED by data-core/emit-astro.mjs — DO NOT EDIT
// 生成時間 ${new Date().toISOString()}
// 由 data-core（positions-auto + manual + door15 + data.js）派生，阅读站的唯一數據真相。
export interface LunItem { dice: string; members?: string[]; target?: string; target_ref?: string; off?: boolean; note?: string; }
export interface Position {
  slug: string; door: number; doorName: string; juan: number; position: number; positionName: string;
  headDice?: string; category?: string; pufen?: string[]; lun?: LunItem[];
  yuanben?: string; shiyi?: string[]; refined?: boolean; isFinal?: boolean;
}
export interface Door { id: number; juan: number; name: string; positionCount: number; intro?: string; }

export const POSITIONS: Position[] = ${lit(POSITIONS)};
export const DOORS: Door[] = ${lit(DOORS)};
export const NAME_TO_SLUG: Record<string, string> = ${lit(nameToSlug)};
`;

const outDir = path.join(ROOT, "src", "data");
fs.mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, "positions.generated.ts");
fs.writeFileSync(outPath, out);
const kb = (fs.statSync(outPath).size / 1024).toFixed(0);
console.log(`✓ src/data/positions.generated.ts  ${kb}KB`);
console.log(`  位次 ${POSITIONS.length} · 門 ${DOORS.length} · 名→slug ${Object.keys(nameToSlug).length} 條`);
